<?php
    header('Content-Type: application/json');
    header('Cache-Control: no-cache');
?>
<?php
    $response = [
        "heading" => "Hello, PHP!",
        "message" => "This response was generated by PHP.",
        "date" => date("D M j H:i:s Y"),
        "currentIP" => $_SERVER['REMOTE_ADDR']
    ];
    
    echo json_encode($response, JSON_PRETTY_PRINT);
?>