#!/usr/bin/env python3

import json
import os
from datetime import datetime
import cgitb
cgitb.enable()

print("Cache-Control: no-cache")
print("Content-type: application/json\n")

print(json.dumps({
    "heading": "Hello, Python!",
    "message": "This response was generated by the Python programming language",
    "date": datetime.now().strftime('%a %b %d %H:%M:%S %Y'),
    "currentIP": os.environ.get('REMOTE_ADDR')
}, indent=4))

