#!/usr/bin/env ruby

puts "Cache-Control: no-cache\n";
puts "Content-type: text/html\n\n";

puts "<html><head><title>Hello CGI World</title></head>";
puts "<body><h1 align=center>Hello CGI World!</h1><hr/>\n";

puts "<p>Hello World</p>\n";
puts "<p>This page was generated by the Ruby programming language</p>\n";
puts "<p>This program was generated at: #{Time.now}</p>\n";
puts "<p>Your current IP address is: #{ENV['REMOTE_ADDR']}</p>\n";

puts "</body></html>\n";
